import "./globals.css";
import { Geist, Geist_Mono, Aboreto, Belleza } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const aboreto = Aboreto({
  weight: "400",
  variable: "--font-aboreto-sans",
  subsets: ["latin"],
});

const belleza = Belleza({
  variable: "--font-belleza-sans",
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${aboreto.variable} ${geistMono.variable} ${geistSans.variable} ${belleza.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
